# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/PIRATES

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/PIRATES

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/PIRATES/CMakeFiles /root/PIRATES/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/PIRATES/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named libWorldBox

# Build rule for target.
libWorldBox: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libWorldBox
.PHONY : libWorldBox

# fast build rule for target.
libWorldBox/fast:
	$(MAKE) -f lib/worldBox/CMakeFiles/libWorldBox.dir/build.make lib/worldBox/CMakeFiles/libWorldBox.dir/build
.PHONY : libWorldBox/fast

#=============================================================================
# Target rules for targets named libServer

# Build rule for target.
libServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libServer
.PHONY : libServer

# fast build rule for target.
libServer/fast:
	$(MAKE) -f lib/server/CMakeFiles/libServer.dir/build.make lib/server/CMakeFiles/libServer.dir/build
.PHONY : libServer/fast

#=============================================================================
# Target rules for targets named libCommon

# Build rule for target.
libCommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libCommon
.PHONY : libCommon

# fast build rule for target.
libCommon/fast:
	$(MAKE) -f lib/common/CMakeFiles/libCommon.dir/build.make lib/common/CMakeFiles/libCommon.dir/build
.PHONY : libCommon/fast

src/client/CClient.o: src/client/CClient.cpp.o
.PHONY : src/client/CClient.o

# target to build an object file
src/client/CClient.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CClient.cpp.o
.PHONY : src/client/CClient.cpp.o

src/client/CClient.i: src/client/CClient.cpp.i
.PHONY : src/client/CClient.i

# target to preprocess a source file
src/client/CClient.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CClient.cpp.i
.PHONY : src/client/CClient.cpp.i

src/client/CClient.s: src/client/CClient.cpp.s
.PHONY : src/client/CClient.s

# target to generate assembly for a file
src/client/CClient.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CClient.cpp.s
.PHONY : src/client/CClient.cpp.s

src/client/CClientPirate.o: src/client/CClientPirate.cpp.o
.PHONY : src/client/CClientPirate.o

# target to build an object file
src/client/CClientPirate.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CClientPirate.cpp.o
.PHONY : src/client/CClientPirate.cpp.o

src/client/CClientPirate.i: src/client/CClientPirate.cpp.i
.PHONY : src/client/CClientPirate.i

# target to preprocess a source file
src/client/CClientPirate.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CClientPirate.cpp.i
.PHONY : src/client/CClientPirate.cpp.i

src/client/CClientPirate.s: src/client/CClientPirate.cpp.s
.PHONY : src/client/CClientPirate.s

# target to generate assembly for a file
src/client/CClientPirate.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CClientPirate.cpp.s
.PHONY : src/client/CClientPirate.cpp.s

src/client/CMap.o: src/client/CMap.cpp.o
.PHONY : src/client/CMap.o

# target to build an object file
src/client/CMap.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CMap.cpp.o
.PHONY : src/client/CMap.cpp.o

src/client/CMap.i: src/client/CMap.cpp.i
.PHONY : src/client/CMap.i

# target to preprocess a source file
src/client/CMap.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CMap.cpp.i
.PHONY : src/client/CMap.cpp.i

src/client/CMap.s: src/client/CMap.cpp.s
.PHONY : src/client/CMap.s

# target to generate assembly for a file
src/client/CMap.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CMap.cpp.s
.PHONY : src/client/CMap.cpp.s

src/client/CPirate.o: src/client/CPirate.cpp.o
.PHONY : src/client/CPirate.o

# target to build an object file
src/client/CPirate.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CPirate.cpp.o
.PHONY : src/client/CPirate.cpp.o

src/client/CPirate.i: src/client/CPirate.cpp.i
.PHONY : src/client/CPirate.i

# target to preprocess a source file
src/client/CPirate.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CPirate.cpp.i
.PHONY : src/client/CPirate.cpp.i

src/client/CPirate.s: src/client/CPirate.cpp.s
.PHONY : src/client/CPirate.s

# target to generate assembly for a file
src/client/CPirate.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/CPirate.cpp.s
.PHONY : src/client/CPirate.cpp.s

src/client/client.o: src/client/client.cpp.o
.PHONY : src/client/client.o

# target to build an object file
src/client/client.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.o
.PHONY : src/client/client.cpp.o

src/client/client.i: src/client/client.cpp.i
.PHONY : src/client/client.i

# target to preprocess a source file
src/client/client.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.i
.PHONY : src/client/client.cpp.i

src/client/client.s: src/client/client.cpp.s
.PHONY : src/client/client.s

# target to generate assembly for a file
src/client/client.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.s
.PHONY : src/client/client.cpp.s

src/server/server.o: src/server/server.cpp.o
.PHONY : src/server/server.o

# target to build an object file
src/server/server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.cpp.o
.PHONY : src/server/server.cpp.o

src/server/server.i: src/server/server.cpp.i
.PHONY : src/server/server.i

# target to preprocess a source file
src/server/server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.cpp.i
.PHONY : src/server/server.cpp.i

src/server/server.s: src/server/server.cpp.s
.PHONY : src/server/server.s

# target to generate assembly for a file
src/server/server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.cpp.s
.PHONY : src/server/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... client"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... libWorldBox"
	@echo "... libServer"
	@echo "... libCommon"
	@echo "... src/client/CClient.o"
	@echo "... src/client/CClient.i"
	@echo "... src/client/CClient.s"
	@echo "... src/client/CClientPirate.o"
	@echo "... src/client/CClientPirate.i"
	@echo "... src/client/CClientPirate.s"
	@echo "... src/client/CMap.o"
	@echo "... src/client/CMap.i"
	@echo "... src/client/CMap.s"
	@echo "... src/client/CPirate.o"
	@echo "... src/client/CPirate.i"
	@echo "... src/client/CPirate.s"
	@echo "... src/client/client.o"
	@echo "... src/client/client.i"
	@echo "... src/client/client.s"
	@echo "... src/server/server.o"
	@echo "... src/server/server.i"
	@echo "... src/server/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

