//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CInteractionArea.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CINTERACTIONAREA_H)
#define _CINTERACTIONAREA_H

#include "EInteractionAreaType.h"

class CInteractionArea {
public:
	EInteractionAreaType e_interaction_area_type;
};

#endif  //_CINTERACTIONAREA_H
