//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CItem.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CITEM_H)
#define _CITEM_H


class CItem {
public:
	string m_strDescription;
	virtual void Use() = 0;
private:
	string m_strName;
	bool m_bIsDroped;
};

#endif  //_CITEM_H
