//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CNetworkMessage.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CNETWORKMESSAGE_H)
#define _CNETWORKMESSAGE_H


class CNetworkMessage {
public:
	string strMessage;
};

#endif  //_CNETWORKMESSAGE_H
