//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CResourceHandler.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CRESOURCEHANDLER_H)
#define _CRESOURCEHANDLER_H


class CResourceHandler {
};

#endif  //_CRESOURCEHANDLER_H
