//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CTools.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CTOOLS_H)
#define _CTOOLS_H


class CTools {
};

#endif  //_CTOOLS_H
