//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CTreasure.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CTREASURE_H)
#define _CTREASURE_H


class CTreasure {
private:
	int m_iValue;
	ETreasureType m_e_treasure_type;
};

#endif  //_CTREASURE_H
