//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CWeapon.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CWEAPON_H)
#define _CWEAPON_H


class CWeapon {
private:
	int m_iPower;
	int m_iRange;
};

#endif  //_CWEAPON_H
