//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CWorldMap.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CWORLDMAP_H)
#define _CWORLDMAP_H


class CWorldMap {
private:
	Array<CInteractionArea> m_ainteractionArea;
	Array<string> m_aTeamName;
};

#endif  //_CWORLDMAP_H
