//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : EInteractionAreaType.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_EINTERACTIONAREATYPE_H)
#define _EINTERACTIONAREATYPE_H


enum EInteractionAreaType {
	e_interaction_area_type_dirt,
	e_interaction_area_type_chest
};

#endif  //_EINTERACTIONAREATYPE_H
