//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ENetworkMessageType.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_ENETWORKMESSAGETYPE_H)
#define _ENETWORKMESSAGETYPE_H


enum ENetworkMessageType {
	e_network_message_new_game,
	e_network_message_new_player,
	e_network_message_error_party_full
};

#endif  //_ENETWORKMESSAGETYPE_H
