//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ETreasuretype.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_ETREASURETYPE_H)
#define _ETREASURETYPE_H


enum ETreasuretype {
};

#endif  //_ETREASURETYPE_H
