//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CClient.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CCLIENT_H)
#define _CCLIENT_H


class CClient {
public:
	CServer* m_pServerInstance;
	CResourceHandler* m_presourceHandler;
	void Initialize();
	void StartServer();
	void SendMessage(int CNetworkMessage networkMessage);
	void CreateNewParty(int int iNbMaxPlayers);
	void JoinParty();
private:
	CClientCharacter * m_pCharacter;
	array<CClientOtherCharacter*> m_aClientOtherCharacter;
	bool m_bIsHost;
};

#endif  //_CCLIENT_H
