//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CClientOtherCharacter.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CCLIENTOTHERCHARACTER_H)
#define _CCLIENTOTHERCHARACTER_H


class CClientOtherCharacter {
};

#endif  //_CCLIENTOTHERCHARACTER_H
