//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CDrawableEntity.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CDRAWABLEENTITY_H)
#define _CDRAWABLEENTITY_H


class CDrawableEntity {
public:
	virtual void DrawElement() = 0;
	void ConvertScreenToWorld();
	void ConvertWorldToScreen();
private:
	int m_iAnimationState;
	sf::vector2f m_vScreenPosition;
	sf::vector2f m_vWorldPosition;
	sf::Texture m_pTexture;
};

#endif  //_CDRAWABLEENTITY_H
