//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CServer.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CSERVER_H)
#define _CSERVER_H

#include "CWorldMap.h"

class CServer {
public:
	void Initialize(int int iNbMaxPlayer);
	void LoopGame();
private:
	CWorldMap m_pMap;
};

#endif  //_CSERVER_H
