//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CTeam.h
//  @ Date : 20/10/2014
//  @ Author : 
//
//


#if !defined(_CTEAM_H)
#define _CTEAM_H


class CTeam {
private:
	int m_aTeamMates;
};

#endif  //_CTEAM_H
